name: translate

# Controls when the workflow will run
on:
  workflow_dispatch:
  push:
    branches:
      - beta

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - uses: Mips2648/plugins-translations@main
        with:
          target_languages: "en_US,es_ES,de_DE,it_IT,pt_PT"